defaults:
  - armory_carla_over_objdet

train_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255
      - _target_: torch.fake_quantize_per_tensor_affine
        _partial_: true
        # (x/1+0).round().clamp(0, 255) * 1
        scale: 1
        zero_point: 0
        quant_min: 0
        quant_max: 255

val_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255
      - _target_: torch.fake_quantize_per_tensor_affine
        _partial_: true
        # (x/1+0).round().clamp(0, 255) * 1
        scale: 1
        zero_point: 0
        quant_min: 0
        quant_max: 255

test_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: mart.transforms.ConvertCocoPolysToMask
      # Add masks of perturbable regions.
      - _target_: mart.transforms.LoadPerturbableMask
        perturb_mask_folder: ${paths.data_dir}/carla_over_obj_det/dev/foreground_mask/
      - _target_: mart.transforms.Denormalize
        center: 0
        scale: 255
      - _target_: torch.fake_quantize_per_tensor_affine
        _partial_: true
        # (x/1+0).round().clamp(0, 255) * 1
        scale: 1
        zero_point: 0
        quant_min: 0
        quant_max: 255
