_target_: mart.nn.CallWith
module:
  _target_: mart.nn.Sum
arg_keys:
  - "losses_and_detections.training.loss_objectness"
  - "losses_and_detections.training.loss_rpn_box_reg"
  - "losses_and_detections.training.loss_classifier"
  - "losses_and_detections.training.loss_box_reg"
kwarg_keys: null
