defaults:
  - modular

module:
  _target_: mart.attack.gain.RoIHeadTargetClass
  # Try to classify as background.
  class_index: 0
  targeted: true
_call_with_args_:
  - box_head.class_logits
  - rpn_predictor.boxes
