_target_: mart.nn.CallWith
module:
  _target_: mart.nn.Sum
_call_with_args_:
  - "losses_and_detections.training.loss_objectness"
  - "losses_and_detections.training.loss_rpn_box_reg"
  - "losses_and_detections.training.loss_classifier"
  - "losses_and_detections.training.loss_box_reg"
