defaults:
  - coco

train_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable

val_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable

test_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
