defaults:
  - coco

num_workers: 1

train_dataset:
  transforms:
    transforms:
      - _target_: torchvision.transforms.ToTensor
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.PadToSquare
        fill: 0.5
      - _target_: mart.transforms.Resize
        size: [416, 416]
      - _target_: mart.transforms.ConvertBoxesToCXCYHW
      - _target_: mart.transforms.RemapLabels
      - _target_: mart.transforms.PackTarget
        num_classes: 80

val_dataset:
  transforms: ${..train_dataset.transforms}

test_dataset:
  transforms: ${..val_dataset.transforms}

collate_fn:
  _target_: hydra.utils.get_method
  path: mart.datamodules.coco.yolo_collate_fn
