_target_: mart.datamodules.LitDataModule
# _convert_: all

train_dataset:
  _target_: torchvision.datasets.FakeData

  size: 1000
  image_size: ???
  num_classes: ???

  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor

val_dataset: ${.train_dataset}
test_dataset: ${.val_dataset}

num_workers: 0

ims_per_batch: ???
world_size: ???
