defaults:
  - fiftyone

train_dataset:
  _target_: mart.datamodules.fiftyone.FiftyOneDataset
  dataset_name: ???
  gt_field: "ground_truth_segmentations"
  sample_tags: []
  label_tags: []
  transforms:
    _target_: mart.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.RandomHorizontalFlip
        p: 0.5
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable

val_dataset:
  _target_: mart.datamodules.fiftyone.FiftyOneDataset
  dataset_name: ???
  gt_field: ${..train_dataset.gt_field}
  sample_tags: []
  label_tags: []
  transforms:
    _target_: mart.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable

test_dataset:
  _target_: mart.datamodules.fiftyone.FiftyOneDataset
  dataset_name: ???
  gt_field: ${..train_dataset.gt_field}
  sample_tags: []
  label_tags: []
  transforms:
    _target_: mart.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ToTensor
      # ConvertCocoPolysToMask must be prior to ConvertInstanceSegmentationToPerturbable.
      - _target_: mart.transforms.ConvertCocoPolysToMask
      - _target_: mart.transforms.ConvertInstanceSegmentationToPerturbable
