# @package model.modules.preprocessor
defaults:
  - tuple_normalizer

transforms:
  transforms:
    - _target_: mart.transforms.GetItems
      keys: ${datamodule.test_dataset.modalities}
    - _target_: mart.transforms.Cat
      dim: 0
    - _target_: torchvision.transforms.Normalize
      mean: 0
      std: 255
