# @package model.modules.preprocessor
defaults:
  - tuple_normalizer

# Convert dictionary input into tensor input, then normalize to [0, 1].
transforms:
  transforms:
    - _target_: mart.transforms.GetItems
      keys: ["rgb"]
    - _target_: mart.transforms.Cat
      dim: 0
    - _target_: torchvision.transforms.Normalize
      mean: 0
      std: 255
