# @package model.modules.preprocessor
_target_: mart.transforms.TupleTransforms
transforms:
  _target_: torchvision.transforms.Compose
  # Normalize to [0, 1].
  transforms:
    - _target_: torchvision.transforms.Normalize
      mean: 0
      std: 255
