# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - attack: null
  - batch_converter: null
  - model_wrapper: null
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

output: ???

hydra:
  output_subdir: null
  run:
    dir: .
