# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - attack: ???
  - batch_converter: ???
  - attack/model_transform: armory_objdet
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

output: ???

hydra:
  output_subdir: null
  run:
    dir: .
