defaults:
  - iterative_sgd
  - initializer: uniform_lp
  - gradient_modifier: sign
  - projector: linf_additive_range
  - objective: misclassification
  - gain: cross_entropy
  - threat_model: additive

optimizer:
  lr: 1

max_iters: 10

initializer:
  eps: 8

projector:
  eps: 8
