defaults:
  - adversary
  - pgd
  - linf
  - composer: additive
  - gradient_modifier: sign
  - gain: cross_entropy
  - objective: misclassification
  - batch_c15n: list

eps: ???
lr: ???
max_iters: ???
