defaults:
  - adversary
  - transform: to_pixel_range_255
  - transform@untransform: to_pixel_range_1
  - perturber: default
  - perturber/initializer: uniform_lp
  - perturber/projector: linf_additive_range
  - composer: additive
  - /optimizer@optimizer: sgd
  - gain: cross_entropy
  - gradient_modifier: sign
  - objective: misclassification
  - enforcer: default
  - enforcer/constraints: [lp, pixel_range]

enforcer:
  constraints:
    lp:
      eps: 8

max_iters: 10

optimizer:
  lr: 1

perturber:
  initializer:
    eps: 8

  projector:
    eps: 8
