defaults:
  - iterative_sgd
  - perturber: batch
  - perturber/initializer: uniform_lp
  - perturber/gradient_modifier: sign
  - perturber/projector: linf_additive_range
  - objective: misclassification
  - gain: cross_entropy
  - threat_model: batch_additive

optimizer:
  lr: 1

max_iters: 10

perturber:
  initializer:
    eps: 8

  projector:
    eps: 8
