defaults:
  - adversary
  - fgm
  - linf
  - data_list_pixel01
  - composer: additive
  - gradient_modifier: sign
  - gain: cross_entropy
  - objective: misclassification
  - batch_c15n: list

eps: ???
max_iters: 1
