defaults:
  - iterative
  - perturber: default
  - perturber/optimizer: sgd
  - perturber/initializer: uniform_lp
  - perturber/gradient_modifier: sign
  - perturber/projector: linf_additive_range
  - objective: misclassification
  - gain: cross_entropy
  - threat_model: additive

max_iters: 10

perturber:
  optimizer:
    lr: 1

  initializer:
    eps: 8

  projector:
    eps: 8
