defaults:
  - adversary
  - optimizer: sgd
  - initializer: uniform_lp
  - gradient_modifier: sign
  - projector: linf_additive_range
  - objective: misclassification
  - gain: cross_entropy
  - composer: additive
  - enforcer: default
  - enforcer/constraints: [lp, pixel_range]

enforcer:
  constraints:
    lp:
      eps: 8

optimizer:
  lr: 1

max_iters: 10

initializer:
  eps: 8

projector:
  eps: 8
