defaults:
  - iterative_sgd
  - perturber: default
  - perturber/initializer: uniform_lp
  - perturber/gradient_modifier: sign
  - perturber/projector: linf_additive_range
  - objective: misclassification
  - gain: cross_entropy
  - threat_model/composer@composer: additive
  - threat_model/enforcer@enforcer: default
  - threat_model/enforcer/constraints@enforcer.constraints: [lp, pixel_range]

enforcer:
  constraints:
    lp:
      eps: 8

optimizer:
  lr: 1

max_iters: 10

perturber:
  initializer:
    eps: 8

  projector:
    eps: 8
