# Scale pixel input in the range of [0,1] to [0,255] for Adversary.
defaults:
  - batch_c15n: list
  - batch_c15n/transform: range_1to255
  - batch_c15n/transform@batch_c15n.untransform: range_255to1
