defaults:
  - batch_c15n: tuple
  - batch_c15n/transform@batch_c15n.transform.transforms: to_pixel_range_255
  - batch_c15n/transform@batch_c15n.untransform.transforms: to_pixel_range_1

batch_c15n:
  transform:
    _target_: mart.transforms.TupleTransforms

  untransform:
    _target_: mart.transforms.TupleTransforms
