defaults:
  - callbacks: [progress_bar]

_target_: mart.attack.Adversary
optimizer: ???
initializer: ???
gradient_modifier: ???
projector: ???
max_iters: ???
callbacks: ???
objective: ???
gain: ???
threat_model: ???
