defaults:
  - adversary
  - /optimizer@optimizer: adam
  - enforcer: default
  - composer: default
  - composer/perturber/initializer: uniform
  - composer/perturber/projector: range
  - composer/modules:
      [pert_rect_size, pert_extract_rect, pert_rect_perspective, overlay]
  - gradient_modifier: sign
  - gain: rcnn_training_loss
  - objective: zero_ap
  - override /callbacks@callbacks: [progress_bar, image_visualizer]

max_iters: ???
lr: ???

optimizer:
  maximize: True
  lr: ${..lr}

enforcer:
  # No constraints with complex renderer in the pipeline.
  # TODO: Constraint on digital perturbation?
  constraints: {}

composer:
  perturber:
    initializer:
      min: 0
      max: 255
    projector:
      min: 0
      max: 255
  sequence:
    seq010:
      pert_rect_size: ["target.coords"]
    seq020:
      pert_extract_rect:
        ["perturbation", "pert_rect_size.height", "pert_rect_size.width"]
    seq040:
      pert_rect_perspective: ["pert_extract_rect", "input", "target.coords"]
    seq050:
      overlay: ["pert_rect_perspective", "input", "target.perturbable_mask"]
