defaults:
  - adversary
  - /optimizer@optimizer: adam
  - enforcer: default
  - composer: default
  - composer/perturber/initializer: uniform
  - composer/perturber/projector: linf
  - composer/modules:
      [
        pert_rect_size,
        pert_extract_rect,
        pert_image_base,
        pert_rect_perspective,
        overlay,
      ]
  - gradient_modifier: sign
  - gain: rcnn_training_loss
  - objective: zero_ap
  - override /callbacks@callbacks: [progress_bar, image_visualizer]

max_iters: ???
lr: ???
eps: ???

optimizer:
  maximize: True
  lr: ${..lr}

enforcer:
  # No constraints with complex renderer in the pipeline.
  # TODO: Constraint on digital perturbation?
  constraints: {}

composer:
  perturber:
    initializer:
      min: ${negate:${....eps}}
      max: ${....eps}
    projector:
      eps: ${....eps}
  modules:
    pert_image_base:
      fpath: ???
  sequence:
    seq010:
      pert_rect_size: ["target.coords"]
    seq020:
      pert_extract_rect:
        ["perturbation", "pert_rect_size.height", "pert_rect_size.width"]
    seq030:
      pert_image_base: ["pert_extract_rect"]
    seq040:
      pert_rect_perspective: ["pert_image_base", "input", "target.coords"]
    seq050:
      overlay: ["pert_rect_perspective", "input", "target.perturbable_mask"]
