defaults:
  - adversary
  - perturber: universal
  - perturber/initializer: constant
  - perturber/optimizer: sgd
  - perturber/composer: random_affine_overlay
  - perturber/gain: rcnn_training_loss
  - perturber/gradient_modifier: sign
  - perturber/projector: range
  - perturber/objective: zero_ap
  - enforcer: default
  - enforcer/constraints: [pixel_range]

# Make a 5-step attack for the demonstration purpose.
max_iters: 1

perturber:
  size: [3, 600, 600]

  initializer:
    constant: 127

  optimizer:
    lr: 1
