defaults:
  - object_detection_patch_adversary

composer:
  modules:
    fake_renderer:
      _target_: mart.attack.composer.FakeRenderer

  sequence:
    seq060:
      # Ignore output from overlay.
      fake_renderer:
        ["pert_extract_rect", "pert_rect_perspective", "target.renderer"]
