defaults:
  - universal
  - perturber: default
  - perturber/initializer: uniform
  - perturber/composer: color_jitter_random_affine_overlay
  - perturber/projector: range
  - optimizer: sgd
  - gain: rcnn_training_loss
  - gradient_modifier: lp_normalizer
  - objective: zero_ap
  - enforcer: default
  - enforcer/constraints: [pixel_range]

max_iters: 1

optimizer:
  lr: 25.5
  momentum: 0.9

perturber:
  size: [3, 416, 416]

  initializer:
    min: 127
    max: 129

  composer:
    degrees: [-15, 15]
    translate: [0, 0]
    scale: [0.25, 0.5]
    shear: null
    brightness: 0.3
    contrast: 0.3
    saturation: 1.0
    hue: 0.1

gradient_modifier:
  p: inf
