# Scale pixel input in the range of [0,1] to [0,255] for Adversary.
defaults:
  - tuple
  - transform@transform.transforms: range_1to255
  - transform@untransform.transforms: range_255to1

transform:
  _target_: mart.transforms.TupleTransforms

untransform:
  _target_: mart.transforms.TupleTransforms
