# @package model
defaults:
  - /optimizer@optimizer: sgd

optimizer: ???

lr_scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.OneCycleLR
    _partial_: true
    total_steps: ${trainer.max_steps}
    max_lr: ${model.optimizer.lr}
    anneal_strategy: cos
  interval: step
  frequency: 1
