_target_: mart_armory.batch_converter.ObjectDetectionBatchConverter
_convert_: partial
input_key: "x"
target_keys:
  y: ["area", "boxes", "id", "image_id", "is_crowd", "labels"]
  y_patch_metadata:
    ["avg_patch_depth", "gs_coords", "mask", "max_depth_perturb_meters"]
transform:
  _target_: torchvision.transforms.Compose
  transforms: # NHWC -> NCHW, the PyTorch format.
    - _target_: torch.permute
      _partial_: true
      dims: [0, 3, 1, 2]
    - _target_: builtins.tuple
      _partial_: true
untransform:
  _target_: torchvision.transforms.Compose
  transforms: # NCHW -> NHWC, the TensorFlow format used in ART.
    - _target_: torch.stack
      _partial_: true
      dim: 0
    - _target_: torch.permute
      _partial_: true
      dims: [0, 2, 3, 1]
