_target_: mart_armory.batch_converter.ObjectDetectionBatchConverter
input_key: "x"
target_keys:
  y: ["area", "boxes", "id", "image_id", "is_crowd", "labels"]
  y_patch_metadata:
    ["avg_patch_depth", "gs_coords", "mask", "max_depth_perturb_meters"]
