defaults:
  - batch_converter/transform@batch_converter.transform.transforms: pixel_1to255
  - batch_converter/transform@batch_converter.untransform.transforms: pixel_255to1
  - override batch_converter: tuple

batch_converter:
  transform:
    _target_: mart.transforms.TupleTransforms

  untransform:
    _target_: mart.transforms.TupleTransforms
