defaults:
  - batch_converter/transform@batch_converter.transform.transforms: to_pixel_range_255
  - batch_converter/transform@batch_converter.untransform.transforms: to_pixel_range_1
  - override batch_converter: tuple

batch_converter:
  transform:
    _target_: mart.transforms.TupleTransforms

  untransform:
    _target_: mart.transforms.TupleTransforms
