# @package model

training_metrics:
  _target_: torchmetrics.MetricCollection
  _convert_: partial # metrics must be a dict
  metrics:
    acc:
      _target_: torchmetrics.Accuracy
      task: multiclass
      num_classes: ${datamodule.num_classes}

validation_metrics: ${.training_metrics}

test_metrics: ${.validation_metrics}
