# @package model

training_metrics:
  _target_: torchmetrics.detection.mean_ap.MeanAveragePrecision

validation_metrics:
  _target_: torchmetrics.detection.mean_ap.MeanAveragePrecision

test_metrics:
  _target_: torchmetrics.collections.MetricCollection
  _convert_: partial
  metrics:
    map:
      _target_: torchmetrics.detection.mean_ap.MeanAveragePrecision
    json:
      _target_: mart.utils.export.CocoPredictionJSON
      prediction_file_name: ${paths.output_dir}/test_prediction.json
      groundtruth_file_name: ${paths.output_dir}/test_groundtruth.json
