# @package model

training_metrics:
  _target_: torchmetrics.detection.MAP
  compute_on_step: false

validation_metrics:
  _target_: torchmetrics.detection.MAP
  compute_on_step: false

test_metrics:
  _target_: torchmetrics.detection.MAP
  compute_on_step: false
