defaults:
  - default
  - functions:
      [
        pert_rect_crop,
        pert_image,
        pert_rect_pad,
        pert_rect_perspective_transform,
        pert_mask,
        additive,
        fake_clamp,
      ]

functions:
  pert_rect_crop:
    order: 0
  pert_image:
    order: 1
  pert_rect_pad:
    order: 2
  pert_rect_perspective_transform:
    order: 3
  pert_mask:
    order: 4
  additive:
    order: 5
  fake_clamp:
    order: 6
