defaults:
  - default
  - functions:
      [
        rect_crop,
        pert_image,
        rect_pad,
        rect_perspective_transform,
        overlay,
        fake_clamp,
      ]

functions:
  rect_crop:
    order: 0
  pert_image:
    order: 1
  rect_pad:
    order: 2
  rect_perspective_transform:
    order: 3
  overlay:
    order: 4
  fake_clamp:
    order: 5
