defaults:
  - default
  - functions:
      [
        pert_rect_crop,
        pert_image_additive,
        pert_rect_pad,
        pert_rect_perspective_transform,
        overlay,
        fake_clamp,
      ]

functions:
  pert_rect_crop:
    order: 0
  pert_image_additive:
    order: 1
  pert_rect_pad:
    order: 2
  pert_rect_perspective_transform:
    order: 3
  overlay:
    order: 4
  fake_clamp:
    order: 5
