defaults:
  - classifier

modules:
  preprocessor:
    # no-op
    _target_: torchvision.transforms.Normalize
    mean: 0
    std: 1

  logits:
    _target_: timm.models.convnext.convnext_tiny
    pretrained: true
