_target_: mart.models.LitModular
_convert_: all

output_preds_key: "preds"
output_target_key: "target"

modules: ???
optimizer: ???

validation_metrics: ${.training_metrics}
# We may use different metrics in test.
# test_metrics: ${.training_metrics}
