defaults:
  - modular

# FIXME: it would be nice to not do this...
output_target_key: "target.list_of_targets"

modules:
  yolo:
    _target_: mart.models.detection.yolo.yolo_darknet
    config_path: ???
    weights_path: null

  loss:
    _target_: mart.nn.Sum

  output:
    _target_: mart.nn.ReturnKwargs

# training metrics are too expensive
training_metrics: null

training_sequence:
  seq010:
    yolo:
      images: "input"
      targets: "target.list_of_targets"

  seq020:
    yolo.process_detections:
      _name_: "preds"
      preds: "yolo.detections"

  seq100:
    loss:
      _call_with_args_:
        - "yolo.overlap"
        - "yolo.confidence"
        - "yolo.classification"

validation_sequence:
  seq010: ${..training_sequence.seq010}
  seq020: ${..training_sequence.seq020}
  seq100: ${..training_sequence.seq100}

test_sequence:
  seq010: ${..validation_sequence.seq010}
  seq020: ${..validation_sequence.seq020}

training_step_log:
  loss: "loss"
  loss_overlap: "yolo.overlap"
  loss_confidence: "yolo.confidence"
  loss_classification: "yolo.classification"

validation_step_log:
  loss: "loss"
  loss_overlap: "yolo.overlap"
  loss_confidence: "yolo.confidence"
  loss_classification: "yolo.classification"

test_step_log: null
