defaults:
  - modular

modules:
  yolov4:
    # XXX: This is so sketchy...
    _target_: torch.hub.load
    repo_or_dir: "AlexeyAB/Yet-Another-YOLOv4-Pytorch"
    trust_repo: False
    model: "yolov4"
    pretrained: True

  loss:
    _target_: mart.nn.Sum

  output:
    _target_: mart.nn.ReturnKwargs

# training sequence does not produce preds/targets
training_metrics: null

training_sequence:
  seq010:
    yolov4:
      _return_as_dict_: ["logits", "loss"]
      x: "input"
      y: "target.packed"

  seq030:
    loss:
      _call_with_args_:
        - yolov4.loss

  seq050:
    output:
      loss: loss

# validation sequence does not produce preds/targets
validation_metrics: null

validation_sequence:
  seq010:
    yolov4:
      _return_as_dict_: ["logits", "loss"]
      x: "input"
      y: "target.packed"

  seq030:
    loss:
      _call_with_args_:
        - yolov4.loss

  seq050:
    output:
      loss: loss

# test sequence does not produce preds/targets
test_metrics: null

test_sequence:
  seq010:
    yolov4:
      _return_as_dict_: ["logits", "loss"]
      x: "input"
      y: "target.packed"

  seq030:
    loss:
      _call_with_args_:
        -  yolov4.loss

  seq050:
    output:
      loss: loss

training_step_log:
  - loss

validation_step_log:
  - loss

test_step_log:
  - loss
