defaults:
  - modular

modules:
  yolo:
    _target_: mart.models.detection.yolo.yolo_darknet
    config_path: ???
    weights_path: null

  loss:
    _target_: mart.nn.Sum

  output:
    _target_: mart.nn.ReturnKwargs

# training metrics are too expensive
training_metrics: null

training_sequence:
  seq010:
    yolo:
      images: "input"
      _train_mode_: False
      _inference_mode_: True

  seq020:
    yolo.process_detections:
      _name_: "preds"
      preds: "yolo"

  seq030:
    yolo:
      _name_: "losses"
      images: "input"
      targets: "target"

  seq100:
    loss:
      _call_with_args_:
        - "losses.overlap"
        - "losses.confidence"
        - "losses.classification"

validation_sequence:
  seq010: ${..training_sequence.seq010}
  seq020: ${..training_sequence.seq020}
  seq030:
    yolo:
      _name_: "losses"
      images: "input"
      targets: "target"
      _train_mode_: False
  seq100: ${..training_sequence.seq100}

test_sequence:
  seq010: ${..validation_sequence.seq010}
  seq020: ${..validation_sequence.seq020}

training_step_log:
  loss: "loss"
  loss_overlap: "losses.overlap"
  loss_confidence: "losses.confidence"
  loss_classification: "losses.classification"

validation_step_log:
  loss: "loss"
  loss_overlap: "losses.overlap"
  loss_confidence: "losses.confidence"
  loss_classification: "losses.classification"

test_step_log: null
