defaults:
  - modular

modules:
  logits:
    _target_: yolov3.main.load_yolov3_model
    device: cpu
    ckpt: false
    mode: eval
    weight_path: ${paths.data_dir}/yolov3_original.pt

  losses:
    _target_: mart.models.yolov3.Loss
    image_size: 416 # FIXME: use ${training_data.transform.image_size}?
    average: True

  loss:
    _target_: mart.nn.Sum

  detections:
    _target_: mart.models.yolov3.Detections
    nms: true
    conf_thres: 0.1
    nms_thres: 0.4

  output:
    _target_: mart.nn.ReturnKwargs

# training sequence does not produce preds/targets
training_metrics: null

training_sequence:
  seq010:
    logits: ["input"]

  seq020:
    losses:
      logits: logits
      targets: target.target
      target_lengths: target.lengths

  seq030:
    loss:
      - losses.total_loss

  seq040:
    output:
      loss: loss
      coord_loss: losses.coord_loss
      obj_loss: losses.obj_loss
      noobj_loss: losses.noobj_loss
      class_loss: losses.class_loss

validation_sequence:
  seq010:
    logits: ["input"]

  seq020:
    losses:
      logits: logits
      targets: target.target
      target_lengths: target.lengths

  seq030:
    loss:
      - losses.total_loss

  seq040:
    detections:
      logits: logits
      targets: target.target
      target_lengths: target.lengths

  seq050:
    output:
      preds: detections.preds
      target: detections.target
      loss: loss
      coord_loss: losses.coord_loss
      obj_loss: losses.obj_loss
      noobj_loss: losses.noobj_loss
      class_loss: losses.class_loss

test_sequence:
  seq010:
    logits: ["input"]

  seq020:
    losses:
      logits: logits
      targets: target.target
      target_lengths: target.lengths

  seq030:
    loss:
      - losses.total_loss

  seq040:
    detections:
      logits: logits
      targets: target.target
      target_lengths: target.lengths

  seq050:
    output:
      preds: detections.preds
      target: detections.target
      loss: loss
      coord_loss: losses.coord_loss
      obj_loss: losses.obj_loss
      noobj_loss: losses.noobj_loss
      class_loss: losses.class_loss

training_step_log:
  - loss
  - coord_loss
  - obj_loss
  - noobj_loss
  - class_loss

validation_step_log: ${.training_step_log}
test_step_log: ${.validation_step_log}
