defaults:
  - /batch_c15n@adversary_connector.batch_c15n: tuple

adversary_connector:
  _target_: mart.callbacks.AdversaryConnector
  adversary: null
  train_adversary: null
  val_adversary: null
  test_adversary: null
